title: Seaplane Games: Learning to code through games
author: Mike
email: maguehrer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am learning how to write code; by modding games, writing my own simple games, and writing a blog, maybe I can help you learn too.

# social links
 # DO NOT include the @ character, or else the build will fail!
github_username:  SeaplaneGames # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
